/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author 963478
 */
public class tela_6 extends javax.swing.JFrame {

    /**
     * Creates new form tela_6
     */
    public tela_6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DINHEIRO = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pagamentos = new javax.swing.JLabel();
        dinheiro = new javax.swing.JLabel();
        cartao = new javax.swing.JLabel();
        cheque = new javax.swing.JLabel();
        troco = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        obs = new javax.swing.JLabel();
        obsField = new javax.swing.JTextField();
        totalField = new javax.swing.JTextField();
        dinheiroField = new javax.swing.JTextField();
        cartaoField = new javax.swing.JTextField();
        chequeField = new javax.swing.JTextField();
        trocoField = new javax.swing.JTextField();
        finalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        DINHEIRO.setBackground(new java.awt.Color(255, 255, 255));
        DINHEIRO.setForeground(new java.awt.Color(255, 255, 255));
        DINHEIRO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 105, 255));

        pagamentos.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        pagamentos.setForeground(new java.awt.Color(255, 255, 255));
        pagamentos.setText("Pagamentos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(pagamentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(pagamentos)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        DINHEIRO.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        dinheiro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dinheiro.setForeground(new java.awt.Color(0, 0, 0));
        dinheiro.setText("DINHEIRO:");
        DINHEIRO.add(dinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        cartao.setBackground(new java.awt.Color(0, 0, 0));
        cartao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cartao.setForeground(new java.awt.Color(0, 0, 0));
        cartao.setText("CARTÃO:");
        DINHEIRO.add(cartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        cheque.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cheque.setForeground(new java.awt.Color(0, 0, 0));
        cheque.setText("CHEQUE:");
        DINHEIRO.add(cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        troco.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        troco.setForeground(new java.awt.Color(0, 0, 0));
        troco.setText("TROCO:");
        DINHEIRO.add(troco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        total.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setText("TOTAL:");
        DINHEIRO.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        obs.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        obs.setForeground(new java.awt.Color(0, 0, 0));
        obs.setText("Obs.:");
        DINHEIRO.add(obs, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 166, -1, -1));

        obsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obsFieldActionPerformed(evt);
            }
        });
        DINHEIRO.add(obsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 164, 330, 130));
        DINHEIRO.add(totalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 150, 30));
        DINHEIRO.add(dinheiroField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 30));
        DINHEIRO.add(cartaoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, 30));
        DINHEIRO.add(chequeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, 30));
        DINHEIRO.add(trocoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 150, 30));

        finalizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        finalizar.setText("Finalizar Venda");
        DINHEIRO.add(finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 190, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DINHEIRO, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DINHEIRO, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void obsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obsFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DINHEIRO;
    private javax.swing.JLabel cartao;
    private javax.swing.JTextField cartaoField;
    private javax.swing.JLabel cheque;
    private javax.swing.JTextField chequeField;
    private javax.swing.JLabel dinheiro;
    private javax.swing.JTextField dinheiroField;
    private javax.swing.JButton finalizar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel obs;
    private javax.swing.JTextField obsField;
    private javax.swing.JLabel pagamentos;
    private javax.swing.JLabel total;
    private javax.swing.JTextField totalField;
    private javax.swing.JLabel troco;
    private javax.swing.JTextField trocoField;
    // End of variables declaration//GEN-END:variables
}
